# Generated by Django 3.0.6 on 2021-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210824_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='media/resume_users/'),
        ),
    ]
