# Generated by Django 3.0.6 on 2021-08-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210831_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='media/resume_users/'),
        ),
    ]
