# Generated by Django 3.0.6 on 2021-09-01 06:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210831_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
